### ISSUE TITLE
dependencies for TYPO3 Version 7.x

### ISSUE THREAD

**Issue by kfumy** [clickstorm/cs_powermail_gdpr#1]
Hi,
I am interested in using the extension, but I have to use TYPO3 7.6.x and powermail 5.x or higher is only for TYPO3 Version 8.7.x. Can you please verify, if your extension is also working for powermail 4.4, the last powermail Version for TYPO3 7.6.x.

Thank a lot
klaus

**Comment by clickstorm** [comment]
Hi,

it's now also tested with powermail 4.0. New version with updated dependencies is available on TER. For powermail 3 we created another branch. 

Kind regards,
Marc
