### ISSUE TITLE
forgotten namespace declaration

### ISSUE THREAD

**Issue by eBornstein** [clickstorm/cs_powermail_gdpr#2]
You forgott the namesspace in Resources/Private/Partials/Form/Field/txCspowermailgdpCheckbox.html

pls add this in first line {namespace vh=In2code\Powermail\ViewHelpers}, else I get this error:
Oops, an error occurred!
Namespace could not be resolved. This exception should never be thrown!

Thanks that's a great extension, has saved my day. ^^

**Comment by mhirdes** [comment]
Thanks for the hint. I removed the view helper, so no namespace is needed. The view helper required a field, which is not set in this case.
